### ISSUE TITLE
Implementierung Klasse "Person"

### ISSUE THREAD

**Issue by Sharky8401** [Sharky8401/Taverne2.0#2]
Oberklasse für alle Arten von Personen oder Wesen die hinzugefügt werden.
Klasse Anforderungen:
-	Attribute:
o	Name (String)
o	Level (Int)
o	Waffen (List) (Dynamisch weil viele Waffen möglich)
o	aktuelleWaffe (int) (Index auf Waffenliste)
o	DefR (int) (Nie 0, Immer automatisch mindestens 1)
o	DefH (int) (Nie 0, immer automatisch mindestens 1)
o	DefS (int)
-	Methoden:
o	Get/Set
o	WaffeHinzufügen
o	WaffeEntfernen
o	WaffeSetzen

**Comment by BlueberryDuck** [comment]
Ich mach das :)
